# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878b5f9cd4c22223b74777023ea87cae484798e02dcc55f5f6fbd007ad43a2fcb896796bf2a6a4c1ba4c1e13b43df9d5a069f56198adc72226934c80f6e061c9

test:
  secret_key_base: d270bcaf4606f9f671e68813bc886942a402959f42e47f52d716836d8f6e37b78ab84d958328da3cdf7afade92e4dcc4389291cc52d9ca085623aad0e9b39d92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
